// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package org.kaaproject.kaa.server.admin.client;
import com.google.gwt.resources.client.CssResource;
import com.google.gwt.resources.client.CssResource.ClassName;
interface KaaAdminTheme extends CssResource {
  
  String actionPopup();
  
  @ClassName("b-app-back-button")
  String bAppBackButton();
  
  @ClassName("b-app-back-button-header")
  String bAppBackButtonHeader();
  
  @ClassName("b-app-back-button-panel")
  String bAppBackButtonPanel();
  
  @ClassName("b-app-button-small")
  String bAppButtonSmall();
  
  @ClassName("b-app-cell-button")
  String bAppCellButton();
  
  @ClassName("b-app-cell-button-small")
  String bAppCellButtonSmall();
  
  @ClassName("b-app-content-close")
  String bAppContentClose();
  
  @ClassName("b-app-content-details-table")
  String bAppContentDetailsTable();
  
  @ClassName("b-app-content-notes")
  String bAppContentNotes();
  
  @ClassName("b-app-content-sub-title")
  String bAppContentSubTitle();
  
  @ClassName("b-app-content-title")
  String bAppContentTitle();
  
  @ClassName("b-app-content-title-label")
  String bAppContentTitleLabel();
  
  @ClassName("b-app-footer")
  String bAppFooter();
  
  @ClassName("b-app-header")
  String bAppHeader();
  
  @ClassName("b-app-header-menu")
  String bAppHeaderMenu();
  
  @ClassName("b-app-header-title")
  String bAppHeaderTitle();
  
  @ClassName("b-app-navigator")
  String bAppNavigator();
  
  @ClassName("b-app-padded-panel")
  String bAppPaddedPanel();
  
  @ClassName("b-app-sub-content")
  String bAppSubContent();
  
  @ClassName("b-app-sub-header")
  String bAppSubHeader();
  
  @ClassName("b-app-sub-header-text")
  String bAppSubHeaderText();
  
  @ClassName("b-app-sub-header-title")
  String bAppSubHeaderTitle();
  
  @ClassName("b-app-sub-navigator")
  String bAppSubNavigator();
  
  @ClassName("b-current")
  String bCurrent();
  
  @ClassName("b-nav-content")
  String bNavContent();
  
  @ClassName("b-nav-label")
  String bNavLabel();
  
  @ClassName("b-nav-panel")
  String bNavPanel();
  
  @ClassName("button-margin-left")
  String buttonMarginLeft();
  
  String caret();
  
  @ClassName("gwt-Label")
  String gwtLabel();
  
  String linkLabel();
  
  String loginButton();
  
  String loginPanel();
  
  String secondary();
}

