/*
 * Copyright 2014 CyberVision, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

# ifndef KAA_DEFAULTS_H_
# define KAA_DEFAULTS_H_

/**
 *
 * DO NOT EDIT THIS FILE. IT IS AUTO-GENERATED.
 *
 */

# include <stdint.h>
# include "kaa_common.h"

# ifdef __cplusplus
extern "C" {
# endif

# define BUILD_VERSION                   "0.6.1-SNAPSHOT"
# define BUILD_COMMIT_HASH               "N/A"

# define APPLICATION_TOKEN               "01234567890123456789"

# define CONFIG_SCHEMA_VERSION           6
# define PROFILE_SCHEMA_VERSION          7
# define SYSTEM_NF_SCHEMA_VERSION        1
# define USER_NF_SCHEMA_VERSION          5
# define LOG_SCHEMA_VERSION              4

# define KAA_SYNC_TIMEOUT                60000L



typedef struct kaa_events_schema_version_ {
    const char *    name;
    uint16_t         version;
} kaa_events_schema_version;

# define KAA_EVENT_SCHEMA_VERSIONS_SIZE    2

static const kaa_events_schema_version KAA_EVENT_SCHEMA_VERSIONS[KAA_EVENT_SCHEMA_VERSIONS_SIZE] =
{
    {
          /* .name = */   "1ecf"
        , /* .version = */3
    },
    {
          /* .name = */   "2ecf"
        , /* .version = */2
    }
};



/**
 * @brief Uses to represent transport-specific connection data to establish
 * connection to Bootstrap servers.
 *
 * @see kaa_transport_protocol_info_t
 * @see kaa_access_point_t
 */
typedef struct {
    kaa_transport_protocol_info_t    protocol_info;
    kaa_access_point_t               access_point; /*!< Connection data of Bootstrap servers is Base64-encoded. */
} kaa_bootstrap_server_connection_data_t;

static const kaa_bootstrap_server_connection_data_t KAA_BOOTSTRAP_ACCESS_POINTS[] =
{
    {
        { 1, 2 },
        {
            12345,
            4,
            "ABCD"
        }
    }
};

# define KAA_BOOTSTRAP_ACCESS_POINT_COUNT    1

# ifdef __cplusplus
} // extern "C"
# endif

# endif /* KAA_DEFAULTS_H_ */

