#!/bin/sh
#
# Copyright 2014-2016 CyberVision, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

if [ "$1" = "1" ]; then
  if [ -d /usr/lib/kaa-flume ]; then
      rm -rf /usr/lib/kaa-flume
  fi
elif [ "$1" = "2" ]; then
      echo "!Upgrade"
      for f in /etc/init.d/kaa-flume-*
      do
        if [ -x $f ]; then
           service_name=$(basename "$f")
           if ! service_loc="$(type -p "service")" || [ -z "$service_loc" ]; then
             invoke-rc.d ${service_name} stop || exit $?
           else
             service ${service_name} stop || exit $?
           fi
        fi
      done
fi

getent group  kaa &>/dev/null || groupadd -r kaa || :
getent passwd kaa &>/dev/null || useradd  -r -g kaa \
                             -M -s /sbin/nologin kaa || :

if [ -f /etc/security/limits.d/flume.conf ]
then
    rm -rf /etc/security/limits.d/flume.conf
fi

touch /etc/security/limits.d/flume.conf

echo "flume - nofile 32768" >> /etc/security/limits.d/flume.conf
echo "flume - nproc 65536" >> /etc/security/limits.d/flume.conf

chmod -R 666 /etc/security/limits.d/flume.conf

