/*
 * Copyright 2014-2015 CyberVision, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

# ifndef KAA_DEFAULTS_H_
# define KAA_DEFAULTS_H_

/**
 *
 * DO NOT EDIT THIS FILE. IT IS AUTO-GENERATED.
 *
 */

# include <stdint.h>
# include "kaa_common.h"

# ifdef __cplusplus
extern "C" {
# endif

# define BUILD_VERSION                   "0.7.0-SNAPSHOT"
# define BUILD_COMMIT_HASH               ""

# define APPLICATION_TOKEN               "60551261774314941628"

# define CONFIG_SCHEMA_VERSION           3
# define PROFILE_SCHEMA_VERSION          2
# define SYSTEM_NF_SCHEMA_VERSION        1
# define USER_NF_SCHEMA_VERSION          1
# define LOG_SCHEMA_VERSION              2

# define KAA_SYNC_TIMEOUT                60000L



typedef struct {
    const char *    name;
    uint16_t         version;
} kaa_events_schema_version_t;

# define KAA_EVENT_SCHEMA_VERSIONS_SIZE    0

static const kaa_events_schema_version_t KAA_EVENT_SCHEMA_VERSIONS[KAA_EVENT_SCHEMA_VERSIONS_SIZE] = {
};



/**
 * @brief Uses to represent transport-specific connection data to establish
 * connection to Bootstrap servers.
 *
 * @see kaa_transport_protocol_id_t
 * @see kaa_access_point_t
 */
typedef struct {
    kaa_transport_protocol_id_t    protocol_id;
    kaa_access_point_t             access_point;
} kaa_bootstrap_server_connection_data_t;

# define KAA_BOOTSTRAP_ACCESS_POINT_COUNT    2

static const kaa_bootstrap_server_connection_data_t KAA_BOOTSTRAP_ACCESS_POINTS[KAA_BOOTSTRAP_ACCESS_POINT_COUNT] =
{
    {
        { 0xfb9a3cf0, 1 },
        {
            0x95f7e40f,
            316,
            (char []) {
            0 , 0 , 1 , 38 , 48 , -126 , 1 , 34 , 48 , 13 , 6 , 9 , 42 , -122 , 72 , -122 , -9 , 13 , 1 , 1 , 1 , 5 , 0 , 3 , -126 , 1 , 15 , 0 , 48 , -126 , 1 , 10 , 2 , -126 , 1 , 1 , 0 , -122 , -64 , 54 , -81 , -31 , 45 , 76 , 15 , 66 , 99 , -21 , -2 , -120 , 64 , 71 , 29 , -110 , 75 , 14 , -14 , -10 , -60 , -127 , -127 , 110 , 44 , 103 , -41 , -72 , -20 , 38 , 1 , 32 , -97 , -36 , 31 , -56 , 67 , 77 , 0 , 68 , 33 , -116 , 120 , 19 , 5 , -65 , -82 , 124 , -89 , -86 , 32 , 60 , -104 , -106 , -90 , -19 , 77 , 84 , 72 , 61 , 11 , 121 , -101 , 11 , -19 , -114 , 99 , 73 , -92 , -52 , 112 , 79 , 2 , -46 , -85 , 41 , 79 , 96 , 12 , 53 , -115 , -106 , -18 , -55 , -47 , 113 , -96 , 122 , -43 , 57 , 25 , -14 , 52 , -90 , -89 , -26 , -25 , 93 , 73 , -77 , 56 , -2 , 50 , 44 , 18 , -51 , -31 , 121 , -76 , -34 , -121 , -91 , -118 , 0 , -4 , 59 , 10 , 51 , 68 , 69 , -106 , 121 , 98 , 42 , -45 , -79 , 127 , -111 , 89 , -44 , 65 , 99 , 28 , -4 , -83 , 69 , -32 , 61 , 58 , -75 , 95 , 56 , 111 , 63 , 62 , 93 , 51 , 39 , -107 , -51 , 79 , -70 , -9 , 101 , 6 , -75 , 96 , 45 , 55 , 62 , -99 , 46 , -45 , -100 , 37 , -116 , 111 , 10 , -2 , 52 , 8 , -41 , 22 , -65 , 122 , -83 , -37 , 20 , -47 , -94 , -113 , 118 , -22 , 9 , 91 , 37 , -64 , 42 , 8 , -80 , 76 , 114 , 43 , 87 , -57 , -41 , 115 , 44 , -16 , -26 , 97 , -126 , -48 , -128 , -77 , 11 , 67 , -18 , 54 , -35 , 44 , -85 , 82 , 101 , -51 , -30 , -67 , -56 , -43 , 84 , -62 , 108 , -55 , -88 , -37 , -14 , 58 , 84 , 122 , -57 , 82 , -69 , 47 , -112 , -80 , 60 , 107 , -45 , 58 , 39 , 69 , 66 , -59 , -87 , 122 , -81 , 27 , -97 , -40 , -33 , 15 , -49 , -66 , 108 , 113 , 2 , 3 , 1 , 0 , 1 , 0 , 0 , 0 , 10 , 49 , 48 , 46 , 50 , 46 , 49 , 46 , 49 , 57 , 51 , 0 , 0 , 38 , -95             }
        }
    },
    {
        { 0x56c8ff92, 1 },
        {
            0x95f7e40f,
            316,
            (char []) {
            0 , 0 , 1 , 38 , 48 , -126 , 1 , 34 , 48 , 13 , 6 , 9 , 42 , -122 , 72 , -122 , -9 , 13 , 1 , 1 , 1 , 5 , 0 , 3 , -126 , 1 , 15 , 0 , 48 , -126 , 1 , 10 , 2 , -126 , 1 , 1 , 0 , -122 , -64 , 54 , -81 , -31 , 45 , 76 , 15 , 66 , 99 , -21 , -2 , -120 , 64 , 71 , 29 , -110 , 75 , 14 , -14 , -10 , -60 , -127 , -127 , 110 , 44 , 103 , -41 , -72 , -20 , 38 , 1 , 32 , -97 , -36 , 31 , -56 , 67 , 77 , 0 , 68 , 33 , -116 , 120 , 19 , 5 , -65 , -82 , 124 , -89 , -86 , 32 , 60 , -104 , -106 , -90 , -19 , 77 , 84 , 72 , 61 , 11 , 121 , -101 , 11 , -19 , -114 , 99 , 73 , -92 , -52 , 112 , 79 , 2 , -46 , -85 , 41 , 79 , 96 , 12 , 53 , -115 , -106 , -18 , -55 , -47 , 113 , -96 , 122 , -43 , 57 , 25 , -14 , 52 , -90 , -89 , -26 , -25 , 93 , 73 , -77 , 56 , -2 , 50 , 44 , 18 , -51 , -31 , 121 , -76 , -34 , -121 , -91 , -118 , 0 , -4 , 59 , 10 , 51 , 68 , 69 , -106 , 121 , 98 , 42 , -45 , -79 , 127 , -111 , 89 , -44 , 65 , 99 , 28 , -4 , -83 , 69 , -32 , 61 , 58 , -75 , 95 , 56 , 111 , 63 , 62 , 93 , 51 , 39 , -107 , -51 , 79 , -70 , -9 , 101 , 6 , -75 , 96 , 45 , 55 , 62 , -99 , 46 , -45 , -100 , 37 , -116 , 111 , 10 , -2 , 52 , 8 , -41 , 22 , -65 , 122 , -83 , -37 , 20 , -47 , -94 , -113 , 118 , -22 , 9 , 91 , 37 , -64 , 42 , 8 , -80 , 76 , 114 , 43 , 87 , -57 , -41 , 115 , 44 , -16 , -26 , 97 , -126 , -48 , -128 , -77 , 11 , 67 , -18 , 54 , -35 , 44 , -85 , 82 , 101 , -51 , -30 , -67 , -56 , -43 , 84 , -62 , 108 , -55 , -88 , -37 , -14 , 58 , 84 , 122 , -57 , 82 , -69 , 47 , -112 , -80 , 60 , 107 , -45 , 58 , 39 , 69 , 66 , -59 , -87 , 122 , -81 , 27 , -97 , -40 , -33 , 15 , -49 , -66 , 108 , 113 , 2 , 3 , 1 , 0 , 1 , 0 , 0 , 0 , 10 , 49 , 48 , 46 , 50 , 46 , 49 , 46 , 49 , 57 , 51 , 0 , 0 , 38 , -96             }
        }
    }};



# define KAA_CONFIGURATION_DATA_LENGTH    18

static const char KAA_CONFIGURATION_DATA[KAA_CONFIGURATION_DATA_LENGTH] =
{
2 , 0 , 49 , -83 , -111 , -125 , 50 , 113 , 66 , 28 , -78 , 36 , -39 , 86 , 80 , -22 , -116 , -42 };

# ifdef __cplusplus
} // extern "C"
# endif

# endif /* KAA_DEFAULTS_H_ */

