/*
 * Copyright 2014 CyberVision, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

# ifndef KAA_DEFAULTS_H_
# define KAA_DEFAULTS_H_

/**
 *
 * DO NOT EDIT THIS FILE. IT IS AUTO-GENERATED.
 *
 */

# include <stdint.h>
# include "kaa_common.h"

# ifdef __cplusplus
extern "C" {
# endif

# define BUILD_VERSION                   "0.6.3-SNAPSHOT"
# define BUILD_COMMIT_HASH               "38e508855bfbd5439b499ccd3b0530e2edc217df"

# define APPLICATION_TOKEN               "93139931170804248968"

# define CONFIG_SCHEMA_VERSION           1
# define PROFILE_SCHEMA_VERSION          2
# define SYSTEM_NF_SCHEMA_VERSION        1
# define USER_NF_SCHEMA_VERSION          1
# define LOG_SCHEMA_VERSION              2

# define KAA_SYNC_TIMEOUT                60000L



typedef struct kaa_events_schema_version_ {
    const char *    name;
    uint16_t         version;
} kaa_events_schema_version;

# define KAA_EVENT_SCHEMA_VERSIONS_SIZE    1

static const kaa_events_schema_version KAA_EVENT_SCHEMA_VERSIONS[KAA_EVENT_SCHEMA_VERSIONS_SIZE] = {
    {
          /* .name = */   "Device Event Class Family"
        , /* .version = */1
    }};

typedef struct kaa_channel_info_t {
    char*              host;
    uint16_t           port;
} kaa_channel_info_t;

typedef struct
 {
    const char *   encoded_public_key; /* Base 64 encoded */
    uint16_t       encoded_public_key_len;
    kaa_channel_info_t channels[KAA_CHANNEL_TYPE_COUNT];
} kaa_bootstrap_server_info_t;

# define KAA_BOOTSTRAP_SERVER_COUNT    1

static const kaa_bootstrap_server_info_t KAA_BOOTSTRAP_SERVERS[KAA_BOOTSTRAP_SERVER_COUNT] = {
{
      /* .encoded_public_key = */    "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAj0YJ9Zq9MylxIJkqL6dugZBQ6pXjA0ZXhNetY1PHbqnySewlG8cwkRdupE/VXBCwHli6m7MQ0IYxnHfbgtVbA9YsQ7bwRVJ+cnEZsU8H+QG/bj+iVTFyB1sK7gi8KSnbL0EkNtJJPlD3bDL+tG2a1WWrt2BsY5RTZ1Pdf/zaF8HiVIyLJ7wHoxS9JqHXBvbKgna32e0Rc9kcOwho90Y6/A6Q2GzB5Lns57ZBI/UhQbXkZcO+uMatLVC4U7j4vfPZdD5/kMu+9jBZb6qTvPhBLkKoZiJ2tncae4DZS3Wr2RgAJwfcX4wl5MQM1fevn9xC1+dhMtuUSDUFU6l+gCa+jQIDAQAB"
    , /* .encoded_public_key_len = */392
    , /* .channels = */              {
                                        { "10.2.1.190", 9889 }
                                    ,
                                        { NULL, 0 }
                                    ,
                                        { "10.2.1.190", 9888 }
                                     }
}};

# ifdef __cplusplus
} // extern "C"
# endif

# endif /* KAA_DEFAULTS_H_ */

