/*
 * Copyright 2014-2015 CyberVision, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.kaaproject.kaa.server.common.core.plugin.generator.common;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.kaaproject.kaa.server.common.core.plugin.def.SdkApiFile;
import org.kaaproject.kaa.server.common.core.plugin.generator.common.entity.GenericEntity;
import org.kaaproject.kaa.server.common.core.plugin.generator.common.entity.SimpleGeneratorEntity;
import org.kaaproject.kaa.server.common.core.plugin.generator.common.entity.TemplateVariable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * The core functionality of any plugin builder.
 *
 * @author Bohdan Khablenko
 * @author Andrew Shvayka
 *
 * @since v1.0.0
 */
public abstract class PluginBuilderCore {

    private static final Logger LOG = LoggerFactory.getLogger(PluginBuilderCore.class);

    private final String name;
    private final String namespace;
    private final String template;

    /**
     * Maps a template variable to the list of entities that form its body.
     */
    private final Map<TemplateVariable, List<GenericEntity>> values = new HashMap<>();

    public PluginBuilderCore(String name, String namespace, String template) {
        this.name = name;
        this.namespace = namespace;
        this.template = template;
        this.addEntity(new SimpleGeneratorEntity(TemplateVariable.NAME, name));
        this.addEntity(new SimpleGeneratorEntity(TemplateVariable.NAMESPACE, namespace));
    }

    public String getName() {
        return this.name;
    }

    public String getNamespace() {
        return this.namespace;
    }

    public String getFqn() {
        return this.namespace + "." + this.name;
    }

    /**
     * Adds a source code entity to be processed later on.
     *
     * @param entity An entity to add
     *
     * @see {@link #insertValues()}
     */
    public void addEntity(GenericEntity entity) {
        List<GenericEntity> entityList = this.values.get(entity.getTemplateVariable());
        if (entityList == null) {
            entityList = new ArrayList<>();
            this.values.put(entity.getTemplateVariable(), entityList);
        }
        entityList.add(entity);
    }

    /**
     * Inserts the values into the entity template.
     *
     * @return The template with the values inserted
     *
     * @see {@link #values}
     */
    protected String insertValues() {

        String template = this.template;

        for (TemplateVariable templateVariable : this.values.keySet()) {
            StringBuilder buffer = new StringBuilder();
            this.values.get(templateVariable).forEach(entity -> {
                buffer.append(entity.getBody());
                if (entity.requiresTermination()) {
                    buffer.append(";\n");
                }
                for (int i = 0; i < entity.emptyLines(); i++) {
                    buffer.append("\n\n");
                }
            });

            template = template.replace(templateVariable.getBody(), buffer.toString());
        }

        // Remove unused template variables from the template
        for (TemplateVariable templateVariable : TemplateVariable.values()) {
            template = template.replace(templateVariable.getBody(), "");
        }

        // Shrink excess blank lines
        return template.replaceAll("\n{3,}+", "\n\n");
    }

    /**
     * Returns an SDK file generated by this plugin builder.
     *
     * @return An SDK file generated by this plugin builder
     */
    protected SdkApiFile build() {
        String fileName = this.getName();
        byte[] fileData = this.insertValues().getBytes();
        return new SdkApiFile(fileName, fileData);
    }

    /**
     * Reads the given file as a string.
     *
     * @param fileName The name of a file to read.
     *
     * @return The given file's content as a string.
     */
    protected static String readFileAsString(String fileName) {
        String result = null;
        try {
            StringBuffer fileData = new StringBuffer();
            InputStream input = Thread.currentThread().getContextClassLoader().getResourceAsStream(fileName);
            BufferedReader reader = new BufferedReader(new InputStreamReader(input));
            char[] buf = new char[1024];
            int numRead = 0;
            while ((numRead = reader.read(buf)) != -1) {
                String readData = String.valueOf(buf, 0, numRead);
                fileData.append(readData);
            }
            reader.close();
            result = fileData.toString();
        } catch (IOException e) {
            LOG.error("Unable to read from specified resource '" + fileName + "'! Error: " + e.getMessage(), e);
        }
        return result;
    }
}
