#ifndef ESP8266_DEFAULTS_H_
#define ESP8266_DEFAULTS_H_

#define KAA_TCP_CHANNEL_IN_BUFFER_SIZE      246
#define KAA_TCP_CHANNEL_OUT_BUFFER_SIZE     1015

#define KAA_TCP_CHANNEL_KEEPALIVE           300

#define KAATCP_PARSER_MAX_MESSAGE_LENGTH    999

#define KAA_MAX_LOG_MESSAGE_LENGTH          247

#endif /* ESP8266_DEFAULTS_H_ */
