/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kaaproject.kaa.server.flume;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Level { 
  DEBUG, ERROR, FATAL, INFO, TRACE, WARN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Level\",\"namespace\":\"org.kaaproject.kaa.server.flume\",\"symbols\":[\"DEBUG\",\"ERROR\",\"FATAL\",\"INFO\",\"TRACE\",\"WARN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
