#!/bin/sh
#
# Copyright 2014-2015 CyberVision, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

if [ "$1" = "0" ]; then
   if [ -x "/etc/init.d/kaa-admin" ]; then
      if ! chkconfig_loc="$(type -p "chkconfig")" || [ -z "$chkconfig_loc" ]; then
        update-rc.d -f kaa-admin remove >/dev/null
      else
        chkconfig --del kaa-admin >/dev/null
      fi
      rm -f /etc/init.d/kaa-admin
      rm -f /etc/default/kaa-admin
   fi
fi

