#!/bin/sh
#
# Copyright 2014 CyberVision, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

if [ "$1" = "1" ]; then
   if [ -d /usr/lib/kaa-admin ]; then
       rm -rf /usr/lib/kaa-admin
   fi
elif [ "$1" = "2" ]; then
   if [ -x "/etc/init.d/kaa-admin" ]; then
       if ! service_loc="$(type -p "service")" || [ -z "$service_loc" ]; then
	  invoke-rc.d kaa-admin stop || exit $?
       else
	  service kaa-admin stop || exit $?
       fi
   fi
fi

getent group  kaa &>/dev/null || groupadd -r kaa || :
getent passwd kaa &>/dev/null || useradd  -r -g kaa \
                             -M -s /sbin/nologin kaa || :
