var annotated =
[
    [ "kaa_access_point_t", "structkaa__access__point__t.html", "structkaa__access__point__t" ],
    [ "kaa_attachment_status_listeners_t", "structkaa__attachment__status__listeners__t.html", "structkaa__attachment__status__listeners__t" ],
    [ "kaa_bootstrap_server_connection_data_t", "structkaa__bootstrap__server__connection__data__t.html", "structkaa__bootstrap__server__connection__data__t" ],
    [ "kaa_bytes_t", "structkaa__bytes__t.html", "structkaa__bytes__t" ],
    [ "kaa_context_t", "structkaa__context__t.html", "structkaa__context__t" ],
    [ "kaa_dns_resolve_info_t", "structkaa__dns__resolve__info__t.html", "structkaa__dns__resolve__info__t" ],
    [ "kaa_dns_resolve_listener_t", "structkaa__dns__resolve__listener__t.html", "structkaa__dns__resolve__listener__t" ],
    [ "kaa_event_listeners_callback_t", "structkaa__event__listeners__callback__t.html", "structkaa__event__listeners__callback__t" ],
    [ "kaa_events_schema_version_t", "structkaa__events__schema__version__t.html", "structkaa__events__schema__version__t" ],
    [ "kaa_log_record_t", "structkaa__log__record__t.html", "structkaa__log__record__t" ],
    [ "kaa_platform_message_reader_t", "structkaa__platform__message__reader__t.html", "structkaa__platform__message__reader__t" ],
    [ "kaa_platform_message_writer_t", "structkaa__platform__message__writer__t.html", "structkaa__platform__message__writer__t" ],
    [ "kaa_serialize_info_t", "structkaa__serialize__info__t.html", "structkaa__serialize__info__t" ],
    [ "kaa_status_t", "structkaa__status__t.html", "structkaa__status__t" ],
    [ "kaa_string_t", "structkaa__string__t.html", "structkaa__string__t" ],
    [ "kaa_transport_channel_interface_t", "structkaa__transport__channel__interface__t.html", "structkaa__transport__channel__interface__t" ],
    [ "kaa_transport_context_t", "structkaa__transport__context__t.html", "structkaa__transport__context__t" ],
    [ "kaa_transport_protocol_id_t", "structkaa__transport__protocol__id__t.html", "structkaa__transport__protocol__id__t" ],
    [ "kaa_union_t", "structkaa__union__t.html", "structkaa__union__t" ],
    [ "kaatcp_connack_t", "structkaatcp__connack__t.html", "structkaatcp__connack__t" ],
    [ "kaatcp_connect_t", "structkaatcp__connect__t.html", "structkaatcp__connect__t" ],
    [ "kaatcp_disconnect_t", "structkaatcp__disconnect__t.html", "structkaatcp__disconnect__t" ],
    [ "kaatcp_kaasync_header_t", "structkaatcp__kaasync__header__t.html", "structkaatcp__kaasync__header__t" ],
    [ "kaatcp_kaasync_t", "structkaatcp__kaasync__t.html", "structkaatcp__kaasync__t" ],
    [ "kaatcp_parser_handlers_t", "structkaatcp__parser__handlers__t.html", "structkaatcp__parser__handlers__t" ],
    [ "kaatcp_parser_t", "structkaatcp__parser__t.html", "structkaatcp__parser__t" ]
];