/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kaaproject.kaa.demo.iotworld.lights.traffic;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum EventType { 
  BUTTON  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EventType\",\"namespace\":\"org.kaaproject.kaa.demo.iotworld.lights.traffic\",\"symbols\":[\"BUTTON\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
