/*
 * Copyright 2014-2015 CyberVision, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kaaproject.kaa.demo.iotworld.lights.traffic;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TrafficLightsLog extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TrafficLightsLog\",\"namespace\":\"org.kaaproject.kaa.demo.iotworld.lights.traffic\",\"fields\":[{\"name\":\"eventType\",\"type\":{\"type\":\"enum\",\"name\":\"EventType\",\"symbols\":[\"BUTTON\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   private org.kaaproject.kaa.demo.iotworld.lights.traffic.EventType eventType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public TrafficLightsLog() {}

  /**
   * All-args constructor.
   */
  public TrafficLightsLog(org.kaaproject.kaa.demo.iotworld.lights.traffic.EventType eventType) {
    this.eventType = eventType;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventType;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventType = (org.kaaproject.kaa.demo.iotworld.lights.traffic.EventType)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'eventType' field.
   */
  public org.kaaproject.kaa.demo.iotworld.lights.traffic.EventType getEventType() {
    return eventType;
  }

  /**
   * Sets the value of the 'eventType' field.
   * @param value the value to set.
   */
  public void setEventType(org.kaaproject.kaa.demo.iotworld.lights.traffic.EventType value) {
    this.eventType = value;
  }

  /** Creates a new TrafficLightsLog RecordBuilder */
  public static org.kaaproject.kaa.demo.iotworld.lights.traffic.TrafficLightsLog.Builder newBuilder() {
    return new org.kaaproject.kaa.demo.iotworld.lights.traffic.TrafficLightsLog.Builder();
  }
  
  /** Creates a new TrafficLightsLog RecordBuilder by copying an existing Builder */
  public static org.kaaproject.kaa.demo.iotworld.lights.traffic.TrafficLightsLog.Builder newBuilder(org.kaaproject.kaa.demo.iotworld.lights.traffic.TrafficLightsLog.Builder other) {
    return new org.kaaproject.kaa.demo.iotworld.lights.traffic.TrafficLightsLog.Builder(other);
  }
  
  /** Creates a new TrafficLightsLog RecordBuilder by copying an existing TrafficLightsLog instance */
  public static org.kaaproject.kaa.demo.iotworld.lights.traffic.TrafficLightsLog.Builder newBuilder(org.kaaproject.kaa.demo.iotworld.lights.traffic.TrafficLightsLog other) {
    return new org.kaaproject.kaa.demo.iotworld.lights.traffic.TrafficLightsLog.Builder(other);
  }
  
  /**
   * RecordBuilder for TrafficLightsLog instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TrafficLightsLog>
    implements org.apache.avro.data.RecordBuilder<TrafficLightsLog> {

    private org.kaaproject.kaa.demo.iotworld.lights.traffic.EventType eventType;

    /** Creates a new Builder */
    private Builder() {
      super(org.kaaproject.kaa.demo.iotworld.lights.traffic.TrafficLightsLog.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.kaaproject.kaa.demo.iotworld.lights.traffic.TrafficLightsLog.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventType)) {
        this.eventType = data().deepCopy(fields()[0].schema(), other.eventType);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing TrafficLightsLog instance */
    private Builder(org.kaaproject.kaa.demo.iotworld.lights.traffic.TrafficLightsLog other) {
            super(org.kaaproject.kaa.demo.iotworld.lights.traffic.TrafficLightsLog.SCHEMA$);
      if (isValidValue(fields()[0], other.eventType)) {
        this.eventType = data().deepCopy(fields()[0].schema(), other.eventType);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'eventType' field */
    public org.kaaproject.kaa.demo.iotworld.lights.traffic.EventType getEventType() {
      return eventType;
    }
    
    /** Sets the value of the 'eventType' field */
    public org.kaaproject.kaa.demo.iotworld.lights.traffic.TrafficLightsLog.Builder setEventType(org.kaaproject.kaa.demo.iotworld.lights.traffic.EventType value) {
      validate(fields()[0], value);
      this.eventType = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'eventType' field has been set */
    public boolean hasEventType() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'eventType' field */
    public org.kaaproject.kaa.demo.iotworld.lights.traffic.TrafficLightsLog.Builder clearEventType() {
      eventType = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public TrafficLightsLog build() {
      try {
        TrafficLightsLog record = new TrafficLightsLog();
        record.eventType = fieldSetFlags()[0] ? this.eventType : (org.kaaproject.kaa.demo.iotworld.lights.traffic.EventType) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
