/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kaaproject.kaa.server.operations.pojo.sync;

/**
 * The Class ClientSync represents sync information sent from client to server.
 */
public class ClientSync {

    /** The request id. */
    private Integer requestId;

    /** The client sync meta data. */
    private ClientSyncMetaData clientSyncMetaData;

    /** The profile sync. */
    private ProfileClientSync profileSync;

    /** The configuration sync. */
    private ConfigurationClientSync configurationSync;

    /** The notification sync. */
    private NotificationClientSync notificationSync;

    /** The user sync. */
    private UserClientSync userSync;

    /** The event sync. */
    private EventClientSync eventSync;

    /** The log sync. */
    private LogClientSync logSync;

    public ClientSync() {
    }

    /**
     * All-args constructor.
     *
     * @param requestId
     *            the request id
     * @param syncRequestMetaData
     *            the sync request meta data
     * @param profileSync
     *            the profile sync request
     * @param configurationSyncRequest
     *            the configuration sync request
     * @param notificationSyncRequest
     *            the notification sync request
     * @param userSyncRequest
     *            the user sync request
     * @param eventSyncRequest
     *            the event sync request
     * @param logSyncRequest
     *            the log sync request
     */
    public ClientSync(java.lang.Integer requestId, org.kaaproject.kaa.server.operations.pojo.sync.ClientSyncMetaData clientSyncMetaData,
            org.kaaproject.kaa.server.operations.pojo.sync.ProfileClientSync profileSync,
            org.kaaproject.kaa.server.operations.pojo.sync.ConfigurationClientSync configurationSync,
            org.kaaproject.kaa.server.operations.pojo.sync.NotificationClientSync notificationSync,
            org.kaaproject.kaa.server.operations.pojo.sync.UserClientSync userSync,
            org.kaaproject.kaa.server.operations.pojo.sync.EventClientSync eventSync,
            org.kaaproject.kaa.server.operations.pojo.sync.LogClientSync logSync) {
        this.requestId = requestId;
        this.clientSyncMetaData = clientSyncMetaData;
        this.profileSync = profileSync;
        this.configurationSync = configurationSync;
        this.notificationSync = notificationSync;
        this.userSync = userSync;
        this.eventSync = eventSync;
        this.logSync = logSync;
    }

    /**
     * Gets the value of the 'requestId' field.
     *
     * @return the request id
     */
    public java.lang.Integer getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the 'requestId' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setRequestId(java.lang.Integer value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the 'clientSyncMetaData' field.
     *
     * @return the client sync meta data
     */
    public org.kaaproject.kaa.server.operations.pojo.sync.ClientSyncMetaData getClientSyncMetaData() {
        return clientSyncMetaData;
    }

    /**
     * Sets the value of the 'clientSyncMetaData' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setClientSyncMetaData(org.kaaproject.kaa.server.operations.pojo.sync.ClientSyncMetaData value) {
        this.clientSyncMetaData = value;
    }

    /**
     * Gets the value of the 'profileSync' field.
     *
     * @return the profile sync
     */
    public org.kaaproject.kaa.server.operations.pojo.sync.ProfileClientSync getProfileSync() {
        return profileSync;
    }

    /**
     * Sets the value of the 'profileSync' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setProfileSync(org.kaaproject.kaa.server.operations.pojo.sync.ProfileClientSync value) {
        this.profileSync = value;
    }

    /**
     * Gets the value of the 'configurationSync' field.
     *
     * @return the configuration sync
     */
    public org.kaaproject.kaa.server.operations.pojo.sync.ConfigurationClientSync getConfigurationSync() {
        return configurationSync;
    }

    /**
     * Sets the value of the 'configurationSync' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setConfigurationSync(org.kaaproject.kaa.server.operations.pojo.sync.ConfigurationClientSync value) {
        this.configurationSync = value;
    }

    /**
     * Gets the value of the 'notificationSync' field.
     *
     * @return the notification sync
     */
    public org.kaaproject.kaa.server.operations.pojo.sync.NotificationClientSync getNotificationSync() {
        return notificationSync;
    }

    /**
     * Sets the value of the 'notificationSync' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setNotificationSync(org.kaaproject.kaa.server.operations.pojo.sync.NotificationClientSync value) {
        this.notificationSync = value;
    }

    /**
     * Gets the value of the 'userSync' field.
     *
     * @return the user sync
     */
    public org.kaaproject.kaa.server.operations.pojo.sync.UserClientSync getUserSync() {
        return userSync;
    }

    /**
     * Sets the value of the 'userSync' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setUserSync(org.kaaproject.kaa.server.operations.pojo.sync.UserClientSync value) {
        this.userSync = value;
    }

    /**
     * Gets the value of the 'eventSync' field.
     *
     * @return the event sync
     */
    public org.kaaproject.kaa.server.operations.pojo.sync.EventClientSync getEventSync() {
        return eventSync;
    }

    /**
     * Sets the value of the 'eventSync' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setEventSync(org.kaaproject.kaa.server.operations.pojo.sync.EventClientSync value) {
        this.eventSync = value;
    }

    /**
     * Gets the value of the 'logSync' field.
     *
     * @return the log sync
     */
    public org.kaaproject.kaa.server.operations.pojo.sync.LogClientSync getLogSync() {
        return logSync;
    }

    /**
     * Sets the value of the 'logSync' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setLogSync(org.kaaproject.kaa.server.operations.pojo.sync.LogClientSync value) {
        this.logSync = value;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((configurationSync == null) ? 0 : configurationSync.hashCode());
        result = prime * result + ((eventSync == null) ? 0 : eventSync.hashCode());
        result = prime * result + ((logSync == null) ? 0 : logSync.hashCode());
        result = prime * result + ((notificationSync == null) ? 0 : notificationSync.hashCode());
        result = prime * result + ((profileSync == null) ? 0 : profileSync.hashCode());
        result = prime * result + ((requestId == null) ? 0 : requestId.hashCode());
        result = prime * result + ((clientSyncMetaData == null) ? 0 : clientSyncMetaData.hashCode());
        result = prime * result + ((userSync == null) ? 0 : userSync.hashCode());
        return result;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        ClientSync other = (ClientSync) obj;
        if (configurationSync == null) {
            if (other.configurationSync != null) {
                return false;
            }
        } else if (!configurationSync.equals(other.configurationSync)) {
            return false;
        }
        if (eventSync == null) {
            if (other.eventSync != null) {
                return false;
            }
        } else if (!eventSync.equals(other.eventSync)) {
            return false;
        }
        if (logSync == null) {
            if (other.logSync != null) {
                return false;
            }
        } else if (!logSync.equals(other.logSync)) {
            return false;
        }
        if (notificationSync == null) {
            if (other.notificationSync != null) {
                return false;
            }
        } else if (!notificationSync.equals(other.notificationSync)) {
            return false;
        }
        if (profileSync == null) {
            if (other.profileSync != null) {
                return false;
            }
        } else if (!profileSync.equals(other.profileSync)) {
            return false;
        }
        if (requestId == null) {
            if (other.requestId != null) {
                return false;
            }
        } else if (!requestId.equals(other.requestId)) {
            return false;
        }
        if (clientSyncMetaData == null) {
            if (other.clientSyncMetaData != null) {
                return false;
            }
        } else if (!clientSyncMetaData.equals(other.clientSyncMetaData)) {
            return false;
        }
        if (userSync == null) {
            if (other.userSync != null) {
                return false;
            }
        } else if (!userSync.equals(other.userSync)) {
            return false;
        }
        return true;
    }
}
