/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kaaproject.kaa.server.operations.pojo.sync;  

public class ConfigurationServerSync{

   private int appStateSeqNumber;
   private org.kaaproject.kaa.server.operations.pojo.sync.SyncResponseStatus responseStatus;
   private java.nio.ByteBuffer confSchemaBody;
   private java.nio.ByteBuffer confDeltaBody;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public ConfigurationServerSync() {}

  /**
   * All-args constructor.
   */
  public ConfigurationServerSync(java.lang.Integer appStateSeqNumber, org.kaaproject.kaa.server.operations.pojo.sync.SyncResponseStatus responseStatus, java.nio.ByteBuffer confSchemaBody, java.nio.ByteBuffer confDeltaBody) {
    this.appStateSeqNumber = appStateSeqNumber;
    this.responseStatus = responseStatus;
    this.confSchemaBody = confSchemaBody;
    this.confDeltaBody = confDeltaBody;
  }

  /**
   * Gets the value of the 'appStateSeqNumber' field.
   */
  public java.lang.Integer getAppStateSeqNumber() {
    return appStateSeqNumber;
  }

  /**
   * Sets the value of the 'appStateSeqNumber' field.
   * @param value the value to set.
   */
  public void setAppStateSeqNumber(java.lang.Integer value) {
    this.appStateSeqNumber = value;
  }

  /**
   * Gets the value of the 'responseStatus' field.
   */
  public org.kaaproject.kaa.server.operations.pojo.sync.SyncResponseStatus getResponseStatus() {
    return responseStatus;
  }

  /**
   * Sets the value of the 'responseStatus' field.
   * @param value the value to set.
   */
  public void setResponseStatus(org.kaaproject.kaa.server.operations.pojo.sync.SyncResponseStatus value) {
    this.responseStatus = value;
  }

  /**
   * Gets the value of the 'confSchemaBody' field.
   */
  public java.nio.ByteBuffer getConfSchemaBody() {
    return confSchemaBody;
  }

  /**
   * Sets the value of the 'confSchemaBody' field.
   * @param value the value to set.
   */
  public void setConfSchemaBody(java.nio.ByteBuffer value) {
    this.confSchemaBody = value;
  }

  /**
   * Gets the value of the 'confDeltaBody' field.
   */
  public java.nio.ByteBuffer getConfDeltaBody() {
    return confDeltaBody;
  }

  /**
   * Sets the value of the 'confDeltaBody' field.
   * @param value the value to set.
   */
  public void setConfDeltaBody(java.nio.ByteBuffer value) {
    this.confDeltaBody = value;
  }
}
