/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kaaproject.kaa.server.operations.pojo.sync;  

public class EndpointAttachResponse {
   private java.lang.String requestId;
   private java.lang.String endpointKeyHash;
   private org.kaaproject.kaa.server.operations.pojo.sync.SyncResponseResultType result;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public EndpointAttachResponse() {}

  /**
   * All-args constructor.
   */
  public EndpointAttachResponse(java.lang.String requestId, java.lang.String endpointKeyHash, org.kaaproject.kaa.server.operations.pojo.sync.SyncResponseResultType result) {
    this.requestId = requestId;
    this.endpointKeyHash = endpointKeyHash;
    this.result = result;
  }

  /**
   * Gets the value of the 'requestId' field.
   */
  public java.lang.String getRequestId() {
    return requestId;
  }

  /**
   * Sets the value of the 'requestId' field.
   * @param value the value to set.
   */
  public void setRequestId(java.lang.String value) {
    this.requestId = value;
  }

  /**
   * Gets the value of the 'endpointKeyHash' field.
   */
  public java.lang.String getEndpointKeyHash() {
    return endpointKeyHash;
  }

  /**
   * Sets the value of the 'endpointKeyHash' field.
   * @param value the value to set.
   */
  public void setEndpointKeyHash(java.lang.String value) {
    this.endpointKeyHash = value;
  }

  /**
   * Gets the value of the 'result' field.
   */
  public org.kaaproject.kaa.server.operations.pojo.sync.SyncResponseResultType getResult() {
    return result;
  }

  /**
   * Sets the value of the 'result' field.
   * @param value the value to set.
   */
  public void setResult(org.kaaproject.kaa.server.operations.pojo.sync.SyncResponseResultType value) {
    this.result = value;
  }
}
