/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kaaproject.kaa.server.operations.pojo.sync;

public class ServerSync {

    private Integer requestId;
    private SyncResponseResultType status;
    private ProfileServerSync profileSync;
    private ConfigurationServerSync configurationSync;
    private NotificationServerSync notificationSync;
    private UserServerSync userSync;
    private EventServerSync eventSync;
    private RedirectServerSync redirectSync;
    private LogServerSync logSync;

    public ServerSync() {
    }

    /**
     * All-args constructor.
     */
    public ServerSync(java.lang.Integer requestId, SyncResponseResultType status, ProfileServerSync profileSync,
            ConfigurationServerSync configurationSync, NotificationServerSync notificationSync, UserServerSync userSync,
            EventServerSync eventSync, RedirectServerSync redirectSync, LogServerSync logSync) {
        this.requestId = requestId;
        this.status = status;
        this.profileSync = profileSync;
        this.configurationSync = configurationSync;
        this.notificationSync = notificationSync;
        this.userSync = userSync;
        this.eventSync = eventSync;
        this.redirectSync = redirectSync;
        this.logSync = logSync;
    }

    /**
     * Gets the value of the 'requestId' field.
     */
    public java.lang.Integer getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the 'requestId' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setRequestId(java.lang.Integer value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the 'status' field.
     */
    public SyncResponseResultType getStatus() {
        return status;
    }

    /**
     * Sets the value of the 'status' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setStatus(SyncResponseResultType value) {
        this.status = value;
    }

    /**
     * Gets the value of the 'profileSyncResponse' field.
     */
    public ProfileServerSync getProfileSync() {
        return profileSync;
    }

    /**
     * Sets the value of the 'profileSyncResponse' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setProfileSync(ProfileServerSync value) {
        this.profileSync = value;
    }

    /**
     * Gets the value of the 'configurationSyncResponse' field.
     */
    public ConfigurationServerSync getConfigurationSync() {
        return configurationSync;
    }

    /**
     * Sets the value of the 'configurationSyncResponse' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setConfigurationSync(ConfigurationServerSync value) {
        this.configurationSync = value;
    }

    /**
     * Gets the value of the 'notificationSyncResponse' field.
     */
    public NotificationServerSync getNotificationSync() {
        return notificationSync;
    }

    /**
     * Sets the value of the 'notificationSyncResponse' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setNotificationSync(NotificationServerSync value) {
        this.notificationSync = value;
    }

    /**
     * Gets the value of the 'userSyncResponse' field.
     */
    public UserServerSync getUserSync() {
        return userSync;
    }

    /**
     * Sets the value of the 'userSyncResponse' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setUserSync(UserServerSync value) {
        this.userSync = value;
    }

    /**
     * Gets the value of the 'eventSyncResponse' field.
     */
    public EventServerSync getEventSync() {
        return eventSync;
    }

    /**
     * Sets the value of the 'eventSyncResponse' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setEventSync(EventServerSync value) {
        this.eventSync = value;
    }

    /**
     * Gets the value of the 'redirectSyncResponse' field.
     */
    public RedirectServerSync getRedirectSync() {
        return redirectSync;
    }

    /**
     * Sets the value of the 'redirectSyncResponse' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setRedirectSync(RedirectServerSync value) {
        this.redirectSync = value;
    }

    /**
     * Gets the value of the 'logSyncResponse' field.
     */
    public LogServerSync getLogSync() {
        return logSync;
    }

    /**
     * Sets the value of the 'logSyncResponse' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setLogSync(LogServerSync value) {
        this.logSync = value;
    }
}
