/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kaaproject.kaa.server.operations.pojo.sync;  

public enum SyncResponseResultType { 
  SUCCESS, FAILURE, PROFILE_RESYNC, REDIRECT  ;
}
