/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kaaproject.kaa.server.operations.pojo.sync;  

public class Topic {
   private java.lang.String id;
   private java.lang.String name;
   private org.kaaproject.kaa.server.operations.pojo.sync.SubscriptionType subscriptionType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public Topic() {}

  /**
   * All-args constructor.
   */
  public Topic(java.lang.String id, java.lang.String name, org.kaaproject.kaa.server.operations.pojo.sync.SubscriptionType subscriptionType) {
    this.id = id;
    this.name = name;
    this.subscriptionType = subscriptionType;
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'subscriptionType' field.
   */
  public org.kaaproject.kaa.server.operations.pojo.sync.SubscriptionType getSubscriptionType() {
    return subscriptionType;
  }

  /**
   * Sets the value of the 'subscriptionType' field.
   * @param value the value to set.
   */
  public void setSubscriptionType(org.kaaproject.kaa.server.operations.pojo.sync.SubscriptionType value) {
    this.subscriptionType = value;
  }

}
