/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kaaproject.kaa.server.operations.pojo.sync;  

public class TopicSubscriptionInfo {
   private org.kaaproject.kaa.server.operations.pojo.sync.Topic topicInfo;
   private int seqNumber;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public TopicSubscriptionInfo() {}

  /**
   * All-args constructor.
   */
  public TopicSubscriptionInfo(org.kaaproject.kaa.server.operations.pojo.sync.Topic topicInfo, java.lang.Integer seqNumber) {
    this.topicInfo = topicInfo;
    this.seqNumber = seqNumber;
  }

  /**
   * Gets the value of the 'topicInfo' field.
   */
  public org.kaaproject.kaa.server.operations.pojo.sync.Topic getTopicInfo() {
    return topicInfo;
  }

  /**
   * Sets the value of the 'topicInfo' field.
   * @param value the value to set.
   */
  public void setTopicInfo(org.kaaproject.kaa.server.operations.pojo.sync.Topic value) {
    this.topicInfo = value;
  }

  /**
   * Gets the value of the 'seqNumber' field.
   */
  public java.lang.Integer getSeqNumber() {
    return seqNumber;
  }

  /**
   * Sets the value of the 'seqNumber' field.
   * @param value the value to set.
   */
  public void setSeqNumber(java.lang.Integer value) {
    this.seqNumber = value;
  }
}
