// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package org.kaaproject.kaa.sandbox.web.client;
import com.google.gwt.resources.client.CssResource;
import com.google.gwt.resources.client.CssResource.ClassName;
interface SandboxTheme extends CssResource {
  
  String action();
  
  String actionPopup();
  
  @ClassName("b-app-back-button")
  String bAppBackButton();
  
  @ClassName("b-app-content-title")
  String bAppContentTitle();
  
  @ClassName("b-app-footer")
  String bAppFooter();
  
  @ClassName("b-app-header-menu")
  String bAppHeaderMenu();
  
  @ClassName("b-app-header-title")
  String bAppHeaderTitle();
  
  @ClassName("b-app-padded-panel")
  String bAppPaddedPanel();
  
  String caret();
  
  String contentLabel();
  
  String contentPanel();
  
  String contentTitleLabel();
  
  String demoProjectsWidget();
  
  String demoProjectWidget();
  
  String descriptionLabel();
  
  String details();
  
  @ClassName("details-inner-bottom")
  String detailsInnerBottom();
  
  @ClassName("details-inner-center")
  String detailsInnerCenter();
  
  @ClassName("details-inner-top")
  String detailsInnerTop();
  
  String featureButton();
  
  @ClassName("featureButton-down")
  String featureButtonDown();
  
  @ClassName("featureButton-down-hovering")
  String featureButtonDownHovering();
  
  @ClassName("platform-image-hover")
  String platformImageHover();
  
  String platformSectionTitle();
  
  String shadowPanel();
  
  String title();
}

