set(CMAKE_SYSTEM_NAME QNX)
set(CMAKE_SYSTEM_VERSION 6.5.0)

set(CMAKE_C_COMPILER $ENV{QNX_HOST}/usr/bin/i486-pc-nto-qnx${CMAKE_SYSTEM_VERSION}-gcc)
set(CMAKE_CXX_COMPILER $ENV{QNX_HOST}/usr/bin/i486-pc-nto-qnx${CMAKE_SYSTEM_VERSION}-g++) 

set(CMAKE_LIBRARY_ARCHITECTURE x86)

set(CMAKE_FIND_ROOT_PATH
        ${CMAKE_FIND_ROOT_PATH}
        $ENV{QNX_TARGET}
        $ENV{QNX_TARGET}/${CMAKE_LIBRARY_ARCHITECTURE})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

add_definitions(-DQNX_650_CPP11_TO_STRING_PATCH)