/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kaaproject.kaa.common.endpoint.protocol;

public class ClientSync {

    private Integer requestId;
    private ClientSyncMetaData syncRequestMetaData;
    private ProfileClientSync profileSyncRequest;
    private ConfigurationClientSync configurationSyncRequest;
    private NotificationClientSync notificationSyncRequest;
    private UserClientSync userSyncRequest;
    private EventClientSync eventSyncRequest;
    private LogClientSync logSyncRequest;

    /**
     * Default constructor. Note that this does not initialize fields to their
     * default values from the schema. If that is desired then one should use
     * {@link \#newBuilder()}.
     */
    public ClientSync() {
    }

    /**
     * All-args constructor.
     */
    public ClientSync(java.lang.Integer requestId, org.kaaproject.kaa.common.endpoint.protocol.ClientSyncMetaData syncRequestMetaData,
            org.kaaproject.kaa.common.endpoint.protocol.ProfileClientSync profileSyncRequest,
            org.kaaproject.kaa.common.endpoint.protocol.ConfigurationClientSync configurationSyncRequest,
            org.kaaproject.kaa.common.endpoint.protocol.NotificationClientSync notificationSyncRequest,
            org.kaaproject.kaa.common.endpoint.protocol.UserClientSync userSyncRequest,
            org.kaaproject.kaa.common.endpoint.protocol.EventClientSync eventSyncRequest,
            org.kaaproject.kaa.common.endpoint.protocol.LogClientSync logSyncRequest) {
        this.requestId = requestId;
        this.syncRequestMetaData = syncRequestMetaData;
        this.profileSyncRequest = profileSyncRequest;
        this.configurationSyncRequest = configurationSyncRequest;
        this.notificationSyncRequest = notificationSyncRequest;
        this.userSyncRequest = userSyncRequest;
        this.eventSyncRequest = eventSyncRequest;
        this.logSyncRequest = logSyncRequest;
    }

    /**
     * Gets the value of the 'requestId' field.
     */
    public java.lang.Integer getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the 'requestId' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setRequestId(java.lang.Integer value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the 'syncRequestMetaData' field.
     */
    public org.kaaproject.kaa.common.endpoint.protocol.ClientSyncMetaData getSyncRequestMetaData() {
        return syncRequestMetaData;
    }

    /**
     * Sets the value of the 'syncRequestMetaData' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setSyncRequestMetaData(org.kaaproject.kaa.common.endpoint.protocol.ClientSyncMetaData value) {
        this.syncRequestMetaData = value;
    }

    /**
     * Gets the value of the 'profileSyncRequest' field.
     */
    public org.kaaproject.kaa.common.endpoint.protocol.ProfileClientSync getProfileSyncRequest() {
        return profileSyncRequest;
    }

    /**
     * Sets the value of the 'profileSyncRequest' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setProfileSyncRequest(org.kaaproject.kaa.common.endpoint.protocol.ProfileClientSync value) {
        this.profileSyncRequest = value;
    }

    /**
     * Gets the value of the 'configurationSyncRequest' field.
     */
    public org.kaaproject.kaa.common.endpoint.protocol.ConfigurationClientSync getConfigurationSyncRequest() {
        return configurationSyncRequest;
    }

    /**
     * Sets the value of the 'configurationSyncRequest' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setConfigurationSyncRequest(org.kaaproject.kaa.common.endpoint.protocol.ConfigurationClientSync value) {
        this.configurationSyncRequest = value;
    }

    /**
     * Gets the value of the 'notificationSyncRequest' field.
     */
    public org.kaaproject.kaa.common.endpoint.protocol.NotificationClientSync getNotificationSyncRequest() {
        return notificationSyncRequest;
    }

    /**
     * Sets the value of the 'notificationSyncRequest' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setNotificationSyncRequest(org.kaaproject.kaa.common.endpoint.protocol.NotificationClientSync value) {
        this.notificationSyncRequest = value;
    }

    /**
     * Gets the value of the 'userSyncRequest' field.
     */
    public org.kaaproject.kaa.common.endpoint.protocol.UserClientSync getUserSyncRequest() {
        return userSyncRequest;
    }

    /**
     * Sets the value of the 'userSyncRequest' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setUserSyncRequest(org.kaaproject.kaa.common.endpoint.protocol.UserClientSync value) {
        this.userSyncRequest = value;
    }

    /**
     * Gets the value of the 'eventSyncRequest' field.
     */
    public org.kaaproject.kaa.common.endpoint.protocol.EventClientSync getEventSyncRequest() {
        return eventSyncRequest;
    }

    /**
     * Sets the value of the 'eventSyncRequest' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setEventSyncRequest(org.kaaproject.kaa.common.endpoint.protocol.EventClientSync value) {
        this.eventSyncRequest = value;
    }

    /**
     * Gets the value of the 'logSyncRequest' field.
     */
    public org.kaaproject.kaa.common.endpoint.protocol.LogClientSync getLogSyncRequest() {
        return logSyncRequest;
    }

    /**
     * Sets the value of the 'logSyncRequest' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setLogSyncRequest(org.kaaproject.kaa.common.endpoint.protocol.LogClientSync value) {
        this.logSyncRequest = value;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((configurationSyncRequest == null) ? 0 : configurationSyncRequest.hashCode());
        result = prime * result + ((eventSyncRequest == null) ? 0 : eventSyncRequest.hashCode());
        result = prime * result + ((logSyncRequest == null) ? 0 : logSyncRequest.hashCode());
        result = prime * result + ((notificationSyncRequest == null) ? 0 : notificationSyncRequest.hashCode());
        result = prime * result + ((profileSyncRequest == null) ? 0 : profileSyncRequest.hashCode());
        result = prime * result + ((requestId == null) ? 0 : requestId.hashCode());
        result = prime * result + ((syncRequestMetaData == null) ? 0 : syncRequestMetaData.hashCode());
        result = prime * result + ((userSyncRequest == null) ? 0 : userSyncRequest.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        ClientSync other = (ClientSync) obj;
        if (configurationSyncRequest == null) {
            if (other.configurationSyncRequest != null) {
                return false;
            }
        } else if (!configurationSyncRequest.equals(other.configurationSyncRequest)) {
            return false;
        }
        if (eventSyncRequest == null) {
            if (other.eventSyncRequest != null) {
                return false;
            }
        } else if (!eventSyncRequest.equals(other.eventSyncRequest)) {
            return false;
        }
        if (logSyncRequest == null) {
            if (other.logSyncRequest != null) {
                return false;
            }
        } else if (!logSyncRequest.equals(other.logSyncRequest)) {
            return false;
        }
        if (notificationSyncRequest == null) {
            if (other.notificationSyncRequest != null) {
                return false;
            }
        } else if (!notificationSyncRequest.equals(other.notificationSyncRequest)) {
            return false;
        }
        if (profileSyncRequest == null) {
            if (other.profileSyncRequest != null) {
                return false;
            }
        } else if (!profileSyncRequest.equals(other.profileSyncRequest)) {
            return false;
        }
        if (requestId == null) {
            if (other.requestId != null) {
                return false;
            }
        } else if (!requestId.equals(other.requestId)) {
            return false;
        }
        if (syncRequestMetaData == null) {
            if (other.syncRequestMetaData != null) {
                return false;
            }
        } else if (!syncRequestMetaData.equals(other.syncRequestMetaData)) {
            return false;
        }
        if (userSyncRequest == null) {
            if (other.userSyncRequest != null) {
                return false;
            }
        } else if (!userSyncRequest.equals(other.userSyncRequest)) {
            return false;
        }
        return true;
    }
}
