/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kaaproject.kaa.common.endpoint.protocol;  

public class ConfigurationClientSync {
   private int appStateSeqNumber;
   private java.nio.ByteBuffer configurationHash;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public ConfigurationClientSync() {}

  /**
   * All-args constructor.
   */
  public ConfigurationClientSync(java.lang.Integer appStateSeqNumber, java.nio.ByteBuffer configurationHash) {
    this.appStateSeqNumber = appStateSeqNumber;
    this.configurationHash = configurationHash;
  }

  /**
   * Gets the value of the 'appStateSeqNumber' field.
   */
  public java.lang.Integer getAppStateSeqNumber() {
    return appStateSeqNumber;
  }

  /**
   * Sets the value of the 'appStateSeqNumber' field.
   * @param value the value to set.
   */
  public void setAppStateSeqNumber(java.lang.Integer value) {
    this.appStateSeqNumber = value;
  }

  /**
   * Gets the value of the 'configurationHash' field.
   */
  public java.nio.ByteBuffer getConfigurationHash() {
    return configurationHash;
  }

  /**
   * Sets the value of the 'configurationHash' field.
   * @param value the value to set.
   */
  public void setConfigurationHash(java.nio.ByteBuffer value) {
    this.configurationHash = value;
  }

@Override
public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + appStateSeqNumber;
    result = prime * result + ((configurationHash == null) ? 0 : configurationHash.hashCode());
    return result;
}

@Override
public boolean equals(Object obj) {
    if (this == obj) {
        return true;
    }
    if (obj == null) {
        return false;
    }
    if (getClass() != obj.getClass()) {
        return false;
    }
    ConfigurationClientSync other = (ConfigurationClientSync) obj;
    if (appStateSeqNumber != other.appStateSeqNumber) {
        return false;
    }
    if (configurationHash == null) {
        if (other.configurationHash != null) {
            return false;
        }
    } else if (!configurationHash.equals(other.configurationHash)) {
        return false;
    }
    return true;
}
}
