/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kaaproject.kaa.common.endpoint.protocol;  

public class EndpointAttachRequest {
   private java.lang.String requestId;
   private java.lang.String endpointAccessToken;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public EndpointAttachRequest() {}

  /**
   * All-args constructor.
   */
  public EndpointAttachRequest(java.lang.String requestId, java.lang.String endpointAccessToken) {
    this.requestId = requestId;
    this.endpointAccessToken = endpointAccessToken;
  }

  /**
   * Gets the value of the 'requestId' field.
   */
  public java.lang.String getRequestId() {
    return requestId;
  }

  /**
   * Sets the value of the 'requestId' field.
   * @param value the value to set.
   */
  public void setRequestId(java.lang.String value) {
    this.requestId = value;
  }

  /**
   * Gets the value of the 'endpointAccessToken' field.
   */
  public java.lang.String getEndpointAccessToken() {
    return endpointAccessToken;
  }

  /**
   * Sets the value of the 'endpointAccessToken' field.
   * @param value the value to set.
   */
  public void setEndpointAccessToken(java.lang.String value) {
    this.endpointAccessToken = value;
  }

@Override
public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((endpointAccessToken == null) ? 0 : endpointAccessToken.hashCode());
    result = prime * result + ((requestId == null) ? 0 : requestId.hashCode());
    return result;
}

@Override
public boolean equals(Object obj) {
    if (this == obj) {
        return true;
    }
    if (obj == null) {
        return false;
    }
    if (getClass() != obj.getClass()) {
        return false;
    }
    EndpointAttachRequest other = (EndpointAttachRequest) obj;
    if (endpointAccessToken == null) {
        if (other.endpointAccessToken != null) {
            return false;
        }
    } else if (!endpointAccessToken.equals(other.endpointAccessToken)) {
        return false;
    }
    if (requestId == null) {
        if (other.requestId != null) {
            return false;
        }
    } else if (!requestId.equals(other.requestId)) {
        return false;
    }
    return true;
}

}
