/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kaaproject.kaa.common.endpoint.protocol;  

public class EventServerSync {
   private org.kaaproject.kaa.common.endpoint.protocol.EventSequenceNumberResponse eventSequenceNumberResponse;
   private java.util.List<org.kaaproject.kaa.common.endpoint.protocol.EventListenersResponse> eventListenersResponses;
   private java.util.List<org.kaaproject.kaa.common.endpoint.protocol.Event> events;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public EventServerSync() {}

  /**
   * All-args constructor.
   */
  public EventServerSync(org.kaaproject.kaa.common.endpoint.protocol.EventSequenceNumberResponse eventSequenceNumberResponse, java.util.List<org.kaaproject.kaa.common.endpoint.protocol.EventListenersResponse> eventListenersResponses, java.util.List<org.kaaproject.kaa.common.endpoint.protocol.Event> events) {
    this.eventSequenceNumberResponse = eventSequenceNumberResponse;
    this.eventListenersResponses = eventListenersResponses;
    this.events = events;
  }

  /**
   * Gets the value of the 'eventSequenceNumberResponse' field.
   */
  public org.kaaproject.kaa.common.endpoint.protocol.EventSequenceNumberResponse getEventSequenceNumberResponse() {
    return eventSequenceNumberResponse;
  }

  /**
   * Sets the value of the 'eventSequenceNumberResponse' field.
   * @param value the value to set.
   */
  public void setEventSequenceNumberResponse(org.kaaproject.kaa.common.endpoint.protocol.EventSequenceNumberResponse value) {
    this.eventSequenceNumberResponse = value;
  }

  /**
   * Gets the value of the 'eventListenersResponses' field.
   */
  public java.util.List<org.kaaproject.kaa.common.endpoint.protocol.EventListenersResponse> getEventListenersResponses() {
    return eventListenersResponses;
  }

  /**
   * Sets the value of the 'eventListenersResponses' field.
   * @param value the value to set.
   */
  public void setEventListenersResponses(java.util.List<org.kaaproject.kaa.common.endpoint.protocol.EventListenersResponse> value) {
    this.eventListenersResponses = value;
  }

  /**
   * Gets the value of the 'events' field.
   */
  public java.util.List<org.kaaproject.kaa.common.endpoint.protocol.Event> getEvents() {
    return events;
  }

  /**
   * Sets the value of the 'events' field.
   * @param value the value to set.
   */
  public void setEvents(java.util.List<org.kaaproject.kaa.common.endpoint.protocol.Event> value) {
    this.events = value;
  }
}
