/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kaaproject.kaa.common.endpoint.protocol;  

public class EventListenersRequest {
   private java.lang.String requestId;
   private java.util.List<java.lang.String> eventClassFQNs;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public EventListenersRequest() {}

  /**
   * All-args constructor.
   */
  public EventListenersRequest(java.lang.String requestId, java.util.List<java.lang.String> eventClassFQNs) {
    this.requestId = requestId;
    this.eventClassFQNs = eventClassFQNs;
  }

  /**
   * Gets the value of the 'requestId' field.
   */
  public java.lang.String getRequestId() {
    return requestId;
  }

  /**
   * Sets the value of the 'requestId' field.
   * @param value the value to set.
   */
  public void setRequestId(java.lang.String value) {
    this.requestId = value;
  }

  /**
   * Gets the value of the 'eventClassFQNs' field.
   */
  public java.util.List<java.lang.String> getEventClassFQNs() {
    return eventClassFQNs;
  }

  /**
   * Sets the value of the 'eventClassFQNs' field.
   * @param value the value to set.
   */
  public void setEventClassFQNs(java.util.List<java.lang.String> value) {
    this.eventClassFQNs = value;
  }

@Override
public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((eventClassFQNs == null) ? 0 : eventClassFQNs.hashCode());
    result = prime * result + ((requestId == null) ? 0 : requestId.hashCode());
    return result;
}

@Override
public boolean equals(Object obj) {
    if (this == obj) {
        return true;
    }
    if (obj == null) {
        return false;
    }
    if (getClass() != obj.getClass()) {
        return false;
    }
    EventListenersRequest other = (EventListenersRequest) obj;
    if (eventClassFQNs == null) {
        if (other.eventClassFQNs != null) {
            return false;
        }
    } else if (!eventClassFQNs.equals(other.eventClassFQNs)) {
        return false;
    }
    if (requestId == null) {
        if (other.requestId != null) {
            return false;
        }
    } else if (!requestId.equals(other.requestId)) {
        return false;
    }
    return true;
}

}
