/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kaaproject.kaa.common.endpoint.protocol;

public class LogEntry {
    private java.nio.ByteBuffer data;

    /**
     * Default constructor. Note that this does not initialize fields to their
     * default values from the schema. If that is desired then one should use
     * {@link \#newBuilder()}.
     */
    public LogEntry() {
    }

    /**
     * All-args constructor.
     */
    public LogEntry(java.nio.ByteBuffer data) {
        this.data = data;
    }

    /**
     * Gets the value of the 'data' field.
     */
    public java.nio.ByteBuffer getData() {
        return data;
    }

    /**
     * Sets the value of the 'data' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setData(java.nio.ByteBuffer value) {
        this.data = value;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((data == null) ? 0 : data.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        LogEntry other = (LogEntry) obj;
        if (data == null) {
            if (other.data != null) {
                return false;
            }
        } else if (!data.equals(other.data)) {
            return false;
        }
        return true;
    }
}
