/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kaaproject.kaa.common.endpoint.protocol;  

public class NotificationServerSync {
   private int appStateSeqNumber;
   private org.kaaproject.kaa.common.endpoint.protocol.SyncResponseStatus responseStatus;
   private java.util.List<org.kaaproject.kaa.common.endpoint.protocol.Notification> notifications;
   private java.util.List<org.kaaproject.kaa.common.endpoint.protocol.Topic> availableTopics;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public NotificationServerSync() {}

  /**
   * All-args constructor.
   */
  public NotificationServerSync(java.lang.Integer appStateSeqNumber, org.kaaproject.kaa.common.endpoint.protocol.SyncResponseStatus responseStatus, java.util.List<org.kaaproject.kaa.common.endpoint.protocol.Notification> notifications, java.util.List<org.kaaproject.kaa.common.endpoint.protocol.Topic> availableTopics) {
    this.appStateSeqNumber = appStateSeqNumber;
    this.responseStatus = responseStatus;
    this.notifications = notifications;
    this.availableTopics = availableTopics;
  }

  /**
   * Gets the value of the 'appStateSeqNumber' field.
   */
  public java.lang.Integer getAppStateSeqNumber() {
    return appStateSeqNumber;
  }

  /**
   * Sets the value of the 'appStateSeqNumber' field.
   * @param value the value to set.
   */
  public void setAppStateSeqNumber(java.lang.Integer value) {
    this.appStateSeqNumber = value;
  }

  /**
   * Gets the value of the 'responseStatus' field.
   */
  public org.kaaproject.kaa.common.endpoint.protocol.SyncResponseStatus getResponseStatus() {
    return responseStatus;
  }

  /**
   * Sets the value of the 'responseStatus' field.
   * @param value the value to set.
   */
  public void setResponseStatus(org.kaaproject.kaa.common.endpoint.protocol.SyncResponseStatus value) {
    this.responseStatus = value;
  }

  /**
   * Gets the value of the 'notifications' field.
   */
  public java.util.List<org.kaaproject.kaa.common.endpoint.protocol.Notification> getNotifications() {
    return notifications;
  }

  /**
   * Sets the value of the 'notifications' field.
   * @param value the value to set.
   */
  public void setNotifications(java.util.List<org.kaaproject.kaa.common.endpoint.protocol.Notification> value) {
    this.notifications = value;
  }

  /**
   * Gets the value of the 'availableTopics' field.
   */
  public java.util.List<org.kaaproject.kaa.common.endpoint.protocol.Topic> getAvailableTopics() {
    return availableTopics;
  }

  /**
   * Sets the value of the 'availableTopics' field.
   * @param value the value to set.
   */
  public void setAvailableTopics(java.util.List<org.kaaproject.kaa.common.endpoint.protocol.Topic> value) {
    this.availableTopics = value;
  }
}
