/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kaaproject.kaa.common.endpoint.protocol;

public class NotificationClientSync {
    private int appStateSeqNumber;
    private java.nio.ByteBuffer topicListHash;
    private java.util.List<org.kaaproject.kaa.common.endpoint.protocol.TopicState> topicStates;
    private java.util.List<java.lang.String> acceptedUnicastNotifications;
    private java.util.List<org.kaaproject.kaa.common.endpoint.protocol.SubscriptionCommand> subscriptionCommands;

    /**
     * Default constructor. Note that this does not initialize fields to their
     * default values from the schema. If that is desired then one should use
     * {@link \#newBuilder()}.
     */
    public NotificationClientSync() {
    }

    /**
     * All-args constructor.
     */
    public NotificationClientSync(java.lang.Integer appStateSeqNumber, java.nio.ByteBuffer topicListHash,
            java.util.List<org.kaaproject.kaa.common.endpoint.protocol.TopicState> topicStates,
            java.util.List<java.lang.String> acceptedUnicastNotifications,
            java.util.List<org.kaaproject.kaa.common.endpoint.protocol.SubscriptionCommand> subscriptionCommands) {
        this.appStateSeqNumber = appStateSeqNumber;
        this.topicListHash = topicListHash;
        this.topicStates = topicStates;
        this.acceptedUnicastNotifications = acceptedUnicastNotifications;
        this.subscriptionCommands = subscriptionCommands;
    }

    /**
     * Gets the value of the 'appStateSeqNumber' field.
     */
    public java.lang.Integer getAppStateSeqNumber() {
        return appStateSeqNumber;
    }

    /**
     * Sets the value of the 'appStateSeqNumber' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setAppStateSeqNumber(java.lang.Integer value) {
        this.appStateSeqNumber = value;
    }

    /**
     * Gets the value of the 'topicListHash' field.
     */
    public java.nio.ByteBuffer getTopicListHash() {
        return topicListHash;
    }

    /**
     * Sets the value of the 'topicListHash' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setTopicListHash(java.nio.ByteBuffer value) {
        this.topicListHash = value;
    }

    /**
     * Gets the value of the 'topicStates' field.
     */
    public java.util.List<org.kaaproject.kaa.common.endpoint.protocol.TopicState> getTopicStates() {
        return topicStates;
    }

    /**
     * Sets the value of the 'topicStates' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setTopicStates(java.util.List<org.kaaproject.kaa.common.endpoint.protocol.TopicState> value) {
        this.topicStates = value;
    }

    /**
     * Gets the value of the 'acceptedUnicastNotifications' field.
     */
    public java.util.List<java.lang.String> getAcceptedUnicastNotifications() {
        return acceptedUnicastNotifications;
    }

    /**
     * Sets the value of the 'acceptedUnicastNotifications' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setAcceptedUnicastNotifications(java.util.List<java.lang.String> value) {
        this.acceptedUnicastNotifications = value;
    }

    /**
     * Gets the value of the 'subscriptionCommands' field.
     */
    public java.util.List<org.kaaproject.kaa.common.endpoint.protocol.SubscriptionCommand> getSubscriptionCommands() {
        return subscriptionCommands;
    }

    public void setSubscriptionCommands(java.util.List<org.kaaproject.kaa.common.endpoint.protocol.SubscriptionCommand> subscriptionCommands) {
        this.subscriptionCommands = subscriptionCommands;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((acceptedUnicastNotifications == null) ? 0 : acceptedUnicastNotifications.hashCode());
        result = prime * result + appStateSeqNumber;
        result = prime * result + ((subscriptionCommands == null) ? 0 : subscriptionCommands.hashCode());
        result = prime * result + ((topicListHash == null) ? 0 : topicListHash.hashCode());
        result = prime * result + ((topicStates == null) ? 0 : topicStates.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        NotificationClientSync other = (NotificationClientSync) obj;
        if (acceptedUnicastNotifications == null) {
            if (other.acceptedUnicastNotifications != null) {
                return false;
            }
        } else if (!acceptedUnicastNotifications.equals(other.acceptedUnicastNotifications)) {
            return false;
        }
        if (appStateSeqNumber != other.appStateSeqNumber) {
            return false;
        }
        if (subscriptionCommands == null) {
            if (other.subscriptionCommands != null) {
                return false;
            }
        } else if (!subscriptionCommands.equals(other.subscriptionCommands)) {
            return false;
        }
        if (topicListHash == null) {
            if (other.topicListHash != null) {
                return false;
            }
        } else if (!topicListHash.equals(other.topicListHash)) {
            return false;
        }
        if (topicStates == null) {
            if (other.topicStates != null) {
                return false;
            }
        } else if (!topicStates.equals(other.topicStates)) {
            return false;
        }
        return true;
    }
}
