/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kaaproject.kaa.common.endpoint.protocol;  

public class RedirectServerSync {
   private java.lang.String dnsName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public RedirectServerSync() {}

  /**
   * All-args constructor.
   */
  public RedirectServerSync(java.lang.String dnsName) {
    this.dnsName = dnsName;
  }

  /**
   * Gets the value of the 'dnsName' field.
   */
  public java.lang.String getDnsName() {
    return dnsName;
  }

  /**
   * Sets the value of the 'dnsName' field.
   * @param value the value to set.
   */
  public void setDnsName(java.lang.String value) {
    this.dnsName = value;
  }

}
