/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kaaproject.kaa.common.endpoint.protocol;  

public enum SyncResponseResultType { 
  SUCCESS, FAILURE, PROFILE_RESYNC, REDIRECT  ;
}
