/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kaaproject.kaa.common.endpoint.protocol;  

public class TopicState {
   private java.lang.String topicId;
   private int seqNumber;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public TopicState() {}

  /**
   * All-args constructor.
   */
  public TopicState(java.lang.String topicId, java.lang.Integer seqNumber) {
    this.topicId = topicId;
    this.seqNumber = seqNumber;
  }

  /**
   * Gets the value of the 'topicId' field.
   */
  public java.lang.String getTopicId() {
    return topicId;
  }

  /**
   * Sets the value of the 'topicId' field.
   * @param value the value to set.
   */
  public void setTopicId(java.lang.String value) {
    this.topicId = value;
  }

  /**
   * Gets the value of the 'seqNumber' field.
   */
  public java.lang.Integer getSeqNumber() {
    return seqNumber;
  }

  /**
   * Sets the value of the 'seqNumber' field.
   * @param value the value to set.
   */
  public void setSeqNumber(java.lang.Integer value) {
    this.seqNumber = value;
  }

@Override
public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + seqNumber;
    result = prime * result + ((topicId == null) ? 0 : topicId.hashCode());
    return result;
}

@Override
public boolean equals(Object obj) {
    if (this == obj) {
        return true;
    }
    if (obj == null) {
        return false;
    }
    if (getClass() != obj.getClass()) {
        return false;
    }
    TopicState other = (TopicState) obj;
    if (seqNumber != other.seqNumber) {
        return false;
    }
    if (topicId == null) {
        if (other.topicId != null) {
            return false;
        }
    } else if (!topicId.equals(other.topicId)) {
        return false;
    }
    return true;
}

}
