#!/bin/sh
#
# Copyright 2014-2016 CyberVision, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

case "$1" in
   purge)
      for f in /etc/init.d/kaa-flume-*
      do
        if [ -x $f ]; then
          service_name=$(basename "$f")
          if ! chkconfig_loc="$(type -p "chkconfig")" || [ -z "$chkconfig_loc" ]; then
            update-rc.d -f $service_name remove >/dev/null || exit 1
          else
            chkconfig --del $service_name >/dev/null || exit 1
          fi
          rm -f /etc/init.d/$service_name
        fi
      done
   ;;
   remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
   ;;
   *)
      echo "postrm called with unknown argument \`\$1'" >&2
      exit 0
   ;;
esac

