/*
 * Copyright 2014-2015 CyberVision, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

# ifndef KAA_DEFAULTS_H_
# define KAA_DEFAULTS_H_

/**
 *
 * DO NOT EDIT THIS FILE. IT IS AUTO-GENERATED.
 *
 */

# include <stdint.h>
# include "kaa_common.h"

# ifdef __cplusplus
extern "C" {
# endif

# define BUILD_VERSION                  "0.7.0-SNAPSHOT"
# define BUILD_COMMIT_HASH              ""

# define APPLICATION_TOKEN              "34021411356093211357"

# define CONFIG_SCHEMA_VERSION          1
# define PROFILE_SCHEMA_VERSION         1
# define SYSTEM_NF_SCHEMA_VERSION       1
# define USER_NF_SCHEMA_VERSION         1
# define LOG_SCHEMA_VERSION             1

# define DEFAULT_USER_VERIFIER_TOKEN    "61037050930367857655"

# define KAA_SYNC_TIMEOUT               60000L



typedef struct {
    const char *    name;
    uint16_t         version;
} kaa_events_schema_version_t;

# define KAA_EVENT_SCHEMA_VERSIONS_SIZE    1

static const kaa_events_schema_version_t KAA_EVENT_SCHEMA_VERSIONS[KAA_EVENT_SCHEMA_VERSIONS_SIZE] = {
    {
          /* .name = */   "Thermostat Event Class Family"
        , /* .version = */1
    }};



/**
 * @brief Uses to represent transport-specific connection data to establish
 * connection to Bootstrap servers.
 *
 * @see kaa_transport_protocol_id_t
 * @see kaa_access_point_t
 */
typedef struct {
    kaa_transport_protocol_id_t    protocol_id;
    kaa_access_point_t             access_point;
} kaa_bootstrap_server_connection_data_t;

# define KAA_BOOTSTRAP_ACCESS_POINT_COUNT    2

static const kaa_bootstrap_server_connection_data_t KAA_BOOTSTRAP_ACCESS_POINTS[KAA_BOOTSTRAP_ACCESS_POINT_COUNT] =
{
    {
        { 0xfb9a3cf0, 1 },
        {
            0x95f7e40f,
            319,
            (char []) {
            0 , 0 , 1 , 38 , 48 , -126 , 1 , 34 , 48 , 13 , 6 , 9 , 42 , -122 , 72 , -122 , -9 , 13 , 1 , 1 , 1 , 5 , 0 , 3 , -126 , 1 , 15 , 0 , 48 , -126 , 1 , 10 , 2 , -126 , 1 , 1 , 0 , -98 , -33 , -94 , -47 , -68 , -90 , -71 , 38 , -2 , -49 , 10 , 64 , 72 , -53 , 99 , -109 , -56 , -86 , 48 , 106 , -125 , 37 , -1 , -100 , -113 , 74 , 82 , 77 , 35 , 39 , 93 , 53 , 63 , -23 , 73 , -6 , -93 , 47 , 124 , -58 , -22 , 51 , -86 , 7 , -15 , -117 , -122 , 106 , 65 , 31 , 104 , 72 , -31 , 32 , 9 , -20 , 115 , 45 , -39 , 73 , 38 , -115 , 15 , 66 , 89 , 42 , 35 , 111 , 35 , 43 , 125 , -49 , 32 , 52 , 108 , 78 , -23 , 77 , -25 , 112 , 36 , 42 , -112 , 54 , -94 , 3 , 71 , -45 , -108 , 40 , 49 , 28 , -17 , -111 , -117 , -81 , -29 , 44 , 95 , -62 , 53 , -116 , -38 , 63 , 105 , 116 , -96 , -79 , -40 , -75 , 34 , -21 , -33 , 124 , -94 , -10 , -60 , -67 , -71 , -30 , 22 , 91 , 114 , -40 , 32 , 20 , -98 , 88 , 92 , -21 , 94 , 8 , 90 , 52 , 99 , -44 , 20 , 55 , 50 , 68 , -19 , 3 , -95 , -126 , -58 , -50 , 24 , -108 , 25 , -91 , -3 , 70 , 64 , -53 , 6 , 89 , -77 , 20 , 6 , 100 , 119 , -27 , -39 , -36 , 18 , 103 , -19 , 97 , 24 , 81 , -36 , 50 , -28 , -47 , 45 , -16 , -69 , -56 , -128 , 76 , -19 , -90 , -34 , -3 , 93 , 82 , -45 , -5 , 124 , -23 , 17 , 8 , -39 , -115 , 38 , -124 , -80 , 7 , -99 , -123 , 35 , 116 , 14 , 51 , -57 , 102 , -2 , -24 , -21 , 33 , -102 , 99 , 33 , -27 , 115 , 74 , -19 , -32 , -113 , -80 , 108 , 90 , -24 , -36 , 71 , -117 , 32 , 100 , 93 , 13 , -104 , -39 , -20 , 9 , 101 , 22 , 75 , 119 , -107 , -123 , 48 , 61 , 18 , -93 , -104 , -4 , -75 , -121 , 77 , 43 , -61 , 87 , -123 , -105 , 49 , -53 , 2 , 3 , 1 , 0 , 1 , 0 , 0 , 0 , 13 , 49 , 57 , 50 , 46 , 49 , 54 , 56 , 46 , 57 , 46 , 50 , 48 , 48 , 0 , 0 , 38 , -95             }
        }
    },
    {
        { 0x56c8ff92, 1 },
        {
            0x95f7e40f,
            319,
            (char []) {
            0 , 0 , 1 , 38 , 48 , -126 , 1 , 34 , 48 , 13 , 6 , 9 , 42 , -122 , 72 , -122 , -9 , 13 , 1 , 1 , 1 , 5 , 0 , 3 , -126 , 1 , 15 , 0 , 48 , -126 , 1 , 10 , 2 , -126 , 1 , 1 , 0 , -98 , -33 , -94 , -47 , -68 , -90 , -71 , 38 , -2 , -49 , 10 , 64 , 72 , -53 , 99 , -109 , -56 , -86 , 48 , 106 , -125 , 37 , -1 , -100 , -113 , 74 , 82 , 77 , 35 , 39 , 93 , 53 , 63 , -23 , 73 , -6 , -93 , 47 , 124 , -58 , -22 , 51 , -86 , 7 , -15 , -117 , -122 , 106 , 65 , 31 , 104 , 72 , -31 , 32 , 9 , -20 , 115 , 45 , -39 , 73 , 38 , -115 , 15 , 66 , 89 , 42 , 35 , 111 , 35 , 43 , 125 , -49 , 32 , 52 , 108 , 78 , -23 , 77 , -25 , 112 , 36 , 42 , -112 , 54 , -94 , 3 , 71 , -45 , -108 , 40 , 49 , 28 , -17 , -111 , -117 , -81 , -29 , 44 , 95 , -62 , 53 , -116 , -38 , 63 , 105 , 116 , -96 , -79 , -40 , -75 , 34 , -21 , -33 , 124 , -94 , -10 , -60 , -67 , -71 , -30 , 22 , 91 , 114 , -40 , 32 , 20 , -98 , 88 , 92 , -21 , 94 , 8 , 90 , 52 , 99 , -44 , 20 , 55 , 50 , 68 , -19 , 3 , -95 , -126 , -58 , -50 , 24 , -108 , 25 , -91 , -3 , 70 , 64 , -53 , 6 , 89 , -77 , 20 , 6 , 100 , 119 , -27 , -39 , -36 , 18 , 103 , -19 , 97 , 24 , 81 , -36 , 50 , -28 , -47 , 45 , -16 , -69 , -56 , -128 , 76 , -19 , -90 , -34 , -3 , 93 , 82 , -45 , -5 , 124 , -23 , 17 , 8 , -39 , -115 , 38 , -124 , -80 , 7 , -99 , -123 , 35 , 116 , 14 , 51 , -57 , 102 , -2 , -24 , -21 , 33 , -102 , 99 , 33 , -27 , 115 , 74 , -19 , -32 , -113 , -80 , 108 , 90 , -24 , -36 , 71 , -117 , 32 , 100 , 93 , 13 , -104 , -39 , -20 , 9 , 101 , 22 , 75 , 119 , -107 , -123 , 48 , 61 , 18 , -93 , -104 , -4 , -75 , -121 , 77 , 43 , -61 , 87 , -123 , -105 , 49 , -53 , 2 , 3 , 1 , 0 , 1 , 0 , 0 , 0 , 13 , 49 , 57 , 50 , 46 , 49 , 54 , 56 , 46 , 57 , 46 , 50 , 48 , 48 , 0 , 0 , 38 , -96             }
        }
    }};



# define KAA_CONFIGURATION_DATA_LENGTH    17

static const char KAA_CONFIGURATION_DATA[KAA_CONFIGURATION_DATA_LENGTH] =
{
0 , 126 , -109 , 111 , -81 , 42 , 21 , 71 , -109 , -121 , 99 , -9 , 48 , -65 , 97 , -86 , 110 };

# ifdef __cplusplus
} // extern "C"
# endif

# endif /* KAA_DEFAULTS_H_ */

