/*
 * Copyright 2014-2015 CyberVision, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.kaaproject.kaa.demo.iotworld.connectedcar;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class RfidLog extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RfidLog\",\"namespace\":\"org.kaaproject.kaa.demo.iotworld.connectedcar\",\"fields\":[{\"name\":\"tag\",\"type\":\"long\"}],\"displayName\":\"Log that contain scanned RFID tag\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   private long tag;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public RfidLog() {}

  /**
   * All-args constructor.
   */
  public RfidLog(java.lang.Long tag) {
    this.tag = tag;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return tag;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: tag = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'tag' field.
   */
  public java.lang.Long getTag() {
    return tag;
  }

  /**
   * Sets the value of the 'tag' field.
   * @param value the value to set.
   */
  public void setTag(java.lang.Long value) {
    this.tag = value;
  }

  /** Creates a new RfidLog RecordBuilder */
  public static org.kaaproject.kaa.demo.iotworld.connectedcar.RfidLog.Builder newBuilder() {
    return new org.kaaproject.kaa.demo.iotworld.connectedcar.RfidLog.Builder();
  }
  
  /** Creates a new RfidLog RecordBuilder by copying an existing Builder */
  public static org.kaaproject.kaa.demo.iotworld.connectedcar.RfidLog.Builder newBuilder(org.kaaproject.kaa.demo.iotworld.connectedcar.RfidLog.Builder other) {
    return new org.kaaproject.kaa.demo.iotworld.connectedcar.RfidLog.Builder(other);
  }
  
  /** Creates a new RfidLog RecordBuilder by copying an existing RfidLog instance */
  public static org.kaaproject.kaa.demo.iotworld.connectedcar.RfidLog.Builder newBuilder(org.kaaproject.kaa.demo.iotworld.connectedcar.RfidLog other) {
    return new org.kaaproject.kaa.demo.iotworld.connectedcar.RfidLog.Builder(other);
  }
  
  /**
   * RecordBuilder for RfidLog instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RfidLog>
    implements org.apache.avro.data.RecordBuilder<RfidLog> {

    private long tag;

    /** Creates a new Builder */
    private Builder() {
      super(org.kaaproject.kaa.demo.iotworld.connectedcar.RfidLog.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.kaaproject.kaa.demo.iotworld.connectedcar.RfidLog.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.tag)) {
        this.tag = data().deepCopy(fields()[0].schema(), other.tag);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing RfidLog instance */
    private Builder(org.kaaproject.kaa.demo.iotworld.connectedcar.RfidLog other) {
            super(org.kaaproject.kaa.demo.iotworld.connectedcar.RfidLog.SCHEMA$);
      if (isValidValue(fields()[0], other.tag)) {
        this.tag = data().deepCopy(fields()[0].schema(), other.tag);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'tag' field */
    public java.lang.Long getTag() {
      return tag;
    }
    
    /** Sets the value of the 'tag' field */
    public org.kaaproject.kaa.demo.iotworld.connectedcar.RfidLog.Builder setTag(long value) {
      validate(fields()[0], value);
      this.tag = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'tag' field has been set */
    public boolean hasTag() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'tag' field */
    public org.kaaproject.kaa.demo.iotworld.connectedcar.RfidLog.Builder clearTag() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public RfidLog build() {
      try {
        RfidLog record = new RfidLog();
        record.tag = fieldSetFlags()[0] ? this.tag : (java.lang.Long) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
