# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Kaa' do
  pod 'CocoaLumberjack'
  pod 'AFNetworking', '~> 3.x'
  pod 'sqlite3'
end

target :KaaTests, :exclusive => true do
  pod 'OCMockito', '~> 2.0.1'
end

