# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'libKaa.a' do
  pod 'CocoaLumberjack'
  pod 'AFNetworking', '~> 1.x'
end

target :KaaTests, :exclusive => true do
  pod 'OCMockito', '~> 2.0.1'
end

