# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Kaa' do
  pod 'CocoaLumberjack', '2.3'
  pod 'AFNetworking', '~> 3.x'
  pod 'sqlite3', :inhibit_warnings => true
  pod 'CommonCrypto', '~> 1.1'
end

target :KaaTests do
  pod 'OCMockito', '~> 2.0.1'
end

